export const data =[
    {
        id:1,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:2,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:3,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:4,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:5,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:6,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:7,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:8,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
    {
        id:9,
        image:"/homebrew.png",
        text:"Directus",
        title:"Sponsor"
    },
]